#!/usr/bin/env python
import re
import subprocess
import runpy
from pathlib import Path
import shutil
import click
import inquirer


@click.group()
def dash():
    """Command line tool to manage the bot."""
    pass


@dash.command()
@click.option(
    "--prefix", "-p", prompt="Prefix to use for bot commands", type=str, default="$"
)
@click.option(
    "--description", "-d", prompt="The bot's description text", type=str, default=""
)
@click.option("--token", "-t", prompt="The bot's access token", type=str)
@click.option("--admins", "-a", prompt="User IDs of Bot admins", type=str, default="")
def init(prefix, description, token, admins):
    """Initialize the bot's configuration."""
    root_dir = Path(__file__).parent.parent

    ### Admin parsing
    admins = ";".join(re.split(r", |,| ", admins))

    ### Module prompt
    module_folder = root_dir / "src" / "dash" / "discord" / "modules"
    all_modules = [file.stem for file in module_folder.glob("*.py")]

    questions = [
        inquirer.Checkbox(
            "mods", message="Select the modules you want to load", choices=all_modules
        )
    ]
    answers = inquirer.prompt(questions)
    modules = ";".join([f"mod.{module}" for module in answers["mods"]])

    questions = [
        inquirer.Checkbox(
            "startup_mods",
            message="Select the modules you want to load on startup",
            choices=answers["mods"],
        )
    ]
    answers = inquirer.prompt(questions)
    startup_modules = ";".join([f"mod.{module}" for module in answers["startup_mods"]])

    ### Save into .env file
    dotenv = root_dir / ".env"
    with dotenv.open(mode="w") as f:
        f.writelines(
            [
                f"BOT_PREFIX={prefix}\n",
                f"BOT_TOKEN={token}\n",
                f"BOT_DESCRIPTION={description}\n",
                f"BOT_ADMINS={admins}\n",
                f"BOT_MODULES={modules}\n",
                f"BOT_STARTUP_MODULES={startup_modules}\n",
            ]
        )

    click.secho("Config initalized successfully.", fg="green")


@dash.command()
@click.option("--message", "-m", prompt="Message to add to the migration", type=str)
def makemigration(message):
    command = ["alembic", "revision", "--autogenerate"]
    if message:
        command += ["-m", message]
    subprocess.run(command)


@dash.command()
@click.argument("ref", required=False, type=str)
def migrate(ref=None):
    command = ["alembic", "upgrade"]
    if ref:
        command.append("ref")
    else:
        command.append("head")
    subprocess.run(command)


@dash.command()
def test():
    subprocess.run("pytest")


@dash.command()
def run():
    runpy.run_module("dash.discord.main", run_name="__main__")


if __name__ == "__main__":
    dash()
